language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text

after_success:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then
      composer require codeclimate/php-test-reporter --no-interaction --dev;
      vendor/bin/test-reporter;
    fi
